#!/bin/bash

USERNAME=${USERNAME:-sharehub}
SHAREPATH=${SHAREPATH:-/sharehub}
WRITABLE=${WRITABLE:-true}
GUEST=${GUEST:-false}
FTP_PASSIVE=$([ "${FTP_PASSIVE}" == "true" ] && echo "YES" || echo "NO")

echo "正在配置 FTP 服务"

mkdir -p /etc/vsftpd

cat >/etc/vsftpd/vsftpd.conf <<EOF
listen=YES
listen_ipv6=NO
connect_from_port_20=YES
dirmessage_enable=YES
xferlog_enable=YES
xferlog_std_format=YES
local_enable=YES
userlist_enable=YES
userlist_file=/etc/vsftpd/user_list
userlist_deny=NO
local_root=$SHAREPATH
chroot_local_user=YES
allow_writeable_chroot=YES
seccomp_sandbox=NO
hide_ids=YES
use_localtime=YES
EOF

# 被动模式
if [ "$FTP_PASSIVE" == "true" ]; then
    cat >>/etc/vsftpd/vsftpd.conf <<EOF
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
pasv_addr_resolve=YES
EOF
fi

# 可写权限
if [ "$WRITABLE" == "true" ]; then
    echo "write_enable=YES" >>/etc/vsftpd/vsftpd.conf
else
    echo "write_enable=NO" >>/etc/vsftpd/vsftpd.conf
fi

# 访客
if [ "$GUEST" == "true" ]; then
    cat >>/etc/vsftpd/vsftpd.conf <<EOF
anonymous_enable=YES
anon_root=$SHAREPATH
no_anon_password=YES
EOF

    if [ "$WRITABLE" == "true" ]; then
        cat >>/etc/vsftpd/vsftpd.conf <<EOF
anon_upload_enable=YES
anon_mkdir_write_enable=YES
anon_other_write_enable=YES
EOF
    fi
else
    echo "anonymous_enable=NO" >>/etc/vsftpd/vsftpd.conf
fi

echo "$USERNAME" >/etc/vsftpd/user_list

echo "启动 FTP 服务器"
exec /usr/sbin/vsftpd /etc/vsftpd/vsftpd.conf
