services:
  ftp:
    build:
      context: .
      dockerfile: Dockerfile.ftp
    image: blazesnow/sharehub:ftp
    container_name: ftp
    restart: unless-stopped
    ports:
      - 20:20
      - 21:21
      - 21100-21110:21100-21110
    environment:
      - USERNAME=blazesnow
      - PASSWORD=password
    volumes:
      - ./data:/data
