services:
  sharehub:
    build:
      context: .
      dockerfile: Dockerfile
    image: blazesnow/sharehub:beta
    container_name: sharehub
    restart: no # unless-stopped
    cap_add:
      - SYS_ADMIN # For NFS
    volumes:
      - ./data:/sharehub
    network_mode: host
    environment:
      AGREE: true
      USERNAME: sharehub
      PASSWORD: password
      SHAREPATH: /sharehub
      WRITABLE: true
      GUEST: false
      TZ: UTC+8
      FTP: true
      FTP_PASSIVE: true
      FTP_PASSIVE_IP: 192.168.3.3
      SFTP: false
      SSH: false
      WEBDAV: false
      SMB: false
      NFS: false
