services:
  ftp:
    build:
      context: .
      dockerfile: Dockerfile.ftp
    image: blazesnow/sharehub:ftp
    container_name: ftp
    restart: no
    ports:
      - 20:20
      - 21:21
      - 21100-21110:21100-21110
    environment:
      - USERNAME=blazesnow
      - PASSWORD=password
    volumes:
      - ./data:/data

  sftp:
    build:
      context: .
      dockerfile: Dockerfile.sftp
    image: blazesnow/sharehub:sftp
    container_name: sftp
    restart: no
    ports:
      - 22:22
    environment:
      - USERNAME=blazesnow
      - PASSWORD=password
    volumes:
      - ./data:/data
