services:
  sharehub:
    build: .
    image: blazesnow/sharehub:dev
    container_name: sharehub
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - SERVICE=ftp
      - USERNAME=user
      - PASSWORD=pass
      # 仅当FTP被动模式有问题时，取消注释并设置为宿主机IP
      # - PASV_ADDRESS=192.168.1.100  
    volumes:
      - ./data:/data
