services:
  ftp:
    build:
      context: .
      dockerfile: Dockerfile.ftp
    image: blazesnow/sharehub:ftp
    container_name: ftp
    restart: always
    ports:
      - 21:21
      - 21000-21010:21000-21010
    environment:
      - USERNAME=blazesnow
      - PASSWORD=password
    volumes:
      - ./data:/data
