FROM debian:12

RUN apt-get update && apt-get install vsftpd -y

COPY ./config/vsftpd.conf /etc/vsftpd.conf

COPY ./entrypoint.sh /srv/entrypoint.sh
RUN chmod 700 /srv/entrypoint.sh

EXPOSE 21 21000-21010

ENTRYPOINT [ "/srv/entrypoint.sh" ]

CMD [ "/usr/sbin/vsftpd","/etc/vsftpd.conf" ]