FROM debian:13

RUN apt-get update && apt-get install pure-ftpd -y

RUN addgroup sharehub

RUN adduser --group sharehub admin

COPY ./config/pure-ftpd.conf /etc/pure-ftpd/pure-ftpd.conf

EXPOSE 21 35000-35999

CMD ["pure-ftpd"]