#!/bin/bash

USERNAME=${USERNAME}
PASSWORD=${PASSWORD}
SHAREPATH=${SHAREPATH}
WRITABLE=${WRITABLE}
GUEST=${GUEST}
TZ=${TZ}
FTP=${FTP}
FTP_PASSIVE=${FTP_PASSIVE}
FTP_PASSIVE_IP=${FTP_PASSIVE_IP}
SSH=${SSH}
SFTP=${SFTP}
WEBDAV=${WEBDAV}
SMB=${SMB}
NFS=${NFS}

if [ "$AGREE" != "true" ]; then
    echo "错误：你必须设置环境变量 AGREE=true 才能启动此容器。"
    exit 1
fi

echo "================================================="
echo "         欢迎使用ShareHub"
echo "================================================="
echo "用户名：$USERNAME"
echo "共享路径：$SHAREPATH"
echo "可写权限：$WRITABLE"
echo "访客模式：$GUEST"
echo "时区：$TZ"
echo "FTP：$FTP"
echo "SSH：$SSH"
echo "SFTP：$SFTP"
echo "WebDAV：$WEBDAV"
echo "SMB：$SMB"
echo "NFS：$NFS"
echo "================================================="

# 设定时区
echo "正在初始化sharehub"
echo "设置时区为：$TZ"
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
echo "$TZ" >/etc/timezone

# 创建用户
echo "创建用户：$USERNAME"
addgroup "sharehub" 2>/dev/null || true
adduser -D -G sharehub -s /bin/bash -h "$SHAREPATH" "$USERNAME" 2>/dev/null || true
echo "$USERNAME:$PASSWORD" | chpasswd

# 创建目录
echo "创建共享目录：$SHAREPATH"
mkdir -p "$SHAREPATH"
chown -R "$USERNAME":sharehub "$SHAREPATH"

if [ "$WRITABLE" == "true" ]; then
    echo "授予共享目录写权限"
    chmod -R 775 "$SHAREPATH"
else
    echo "设置共享目录为只读权限"
    chmod -R 555 "$SHAREPATH"
fi

# 启用服务
mkdir -p /etc/s6-overlay/s6-rc.d/user/contents.d

if [ "$FTP" = "true" ]; then
    /srv/init/ftp.sh
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/ftp
fi

if [ "$SFTP" = "true" ] || [ "$SSH" = "true" ]; then
    /srv/init/sftp.sh
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/sftp
fi

if [ "$WEBDAV" = "true" ]; then
    /srv/init/webdav.sh
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/webdav
fi

if [ "$SMB" = "true" ]; then
    /srv/init/smb.sh
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/smb
fi

if [ "$NFS" = "true" ]; then
    /srv/init/nfs.sh
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/nfs-bundle
fi
