services:
  ftp:
    build:
      context: .
      dockerfile: Dockerfile
    image: blazesnow/sharehub:ftp
    container_name: ftp
    restart: no
    ports:
      - 21:21
      - 35000-35999:35000-35999
