name: SMB

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true
        default: ':beta'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: blazesnow
        password: ${{ secrets.TOKEN }}

    - name: Login to GitHub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: samba
        file: Dockerfile
        push: true
        tags: |
          blazesnow/sharehub-smb${{ inputs.tag }}
          ghcr.io/blazesnow/sharehub-smb${{ inputs.tag }}
